version: '3.5'

services:
  db:
    container_name: sidestory_db
    image: mysql:latest
    ports:
      - "5555:3306"
    environment:
      MYSQL_ROOT_PASSWORD: QWERTY
      MYSQL_DATABASE: sidestory_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: QWERTY
    volumes:
      - "./mysql/data.sql:/docker-entrypoint-initdb.d/1.sql"

  redis:
    container_name: redis_nosql
    image: redis:latest
    ports:
      - "6379:6379"